##################################################################
# Lunge rates and prey consumption calculations and visualizations ----
##################################################################

# load data and packages and fuctions 
library(data.table)
library(readxl)
library(forcats)
library(tidyverse)
library(ggstance)
library(mgcv)
library(lme4)
library(lmerTest)
library(MuMIn)
library(ggpubr)


SE = function(x){sd(x)/sqrt(sum(!is.na(x)))}

# Abbreviate a binomial e.g. Balaenoptera musculus -> B. musculus
abbr_binom <- function(binom) {
  paste(str_sub(binom, 1, 1), 
        str_extract(binom, " .*"), 
        sep = ".")
}

# Raincloud plot code----
### This script creates an R function to generate raincloud plots, then simulates
### data for plots. If using for your own data, you only need lines 1-80.
### It relies largely dddon code previously written by David Robinson
### (https://gist.github.com/dgrtwo/eb7750e74997891d7c20)
### and the package ggplot2 by Hadley Wickham

# Check if required packages are installed  
packages <- c("cowplot", "readr", "ggplot2", "dplyr", "lavaan", "smooth", "Hmisc")
if (length(setdiff(packages, rownames(installed.packages()))) > 0) {
  install.packages(setdiff(packages, rownames(installed.packages())))
}

# Load packages
library(ggplot2)
# Defining the geom_flat_violin (Raincloud) function ----
# Note: the below code modifies the
# existing github page by removing a parenthesis in line 50

"%||%" <- function(a, b) {
  if (!is.null(a)) a else b
}

geom_flat_violin <- function(mapping = NULL, data = NULL, stat = "ydensity",
                             position = "dodge", trim = TRUE, scale = "area",
                             show.legend = NA, inherit.aes = TRUE, ...) {
  layer(
    data = data,
    mapping = mapping,
    stat = stat,
    geom = GeomFlatViolin,
    position = position,
    show.legend = show.legend,
    inherit.aes = inherit.aes,
    params = list(
      trim = trim,
      scale = scale,
      ...
    )
  )
}

#' @rdname ggplot2-ggproto
#' @format NULL
#' @usage NULL
#' @export
GeomFlatViolin <-
  ggproto("GeomFlatViolin", Geom,
          setup_data = function(data, params) {
            data$width <- data$width %||%
              params$width %||% (resolution(data$x, FALSE) * 0.9)
            
            # ymin, ymax, xmin, and xmax define the bounding rectangle for each group
            data %>%
              group_by(group) %>%
              mutate(
                ymin = min(y),
                ymax = max(y),
                xmin = x,
                xmax = x + width / 2
              )
          },
          
          draw_group = function(data, panel_scales, coord) {
            # Find the points for the line to go all the way around
            data <- transform(data,
                              xminv = x,
                              xmaxv = x + violinwidth * (xmax - x)
            )
            
            # Make sure it's sorted properly to draw the outline
            newdata <- rbind(
              plyr::arrange(transform(data, x = xminv), y),
              plyr::arrange(transform(data, x = xmaxv), -y)
            )
            
            # Close the polygon: set first and last point the same
            # Needed for coord_polar and such
            newdata <- rbind(newdata, newdata[1, ])
            
            ggplot2:::ggname("geom_flat_violin", GeomPolygon$draw_panel(newdata, panel_scales, coord))
          },
          
          draw_key = draw_key_polygon,
          
          default_aes = aes(
            weight = 1, colour = "grey20", fill = "white", size = 0.5,
            alpha = NA, linetype = "solid"
          ),
          
          required_aes = c("x", "y")
  )







# # feeding rates generated by Max----

# for CATS data
load("~/Documents/Research Data/Whale research/ShirelCh2/rates_CATS.RData")

lunge_rates_CATS <- lunge_rates %>% 
  mutate_at(vars(Rate), ~replace(., is.nan(.), 0)) %>% 
  mutate(tag_type = "CATS")


# for DTAG data

load("~/Documents/Research Data/Whale research/ShirelCh2/rates_DTAG only_9.17.19_long.RData")
  
lunge_rates_DTAG <- dtag_lunges_long %>% 
 mutate_at(vars(Rate), ~replace(., is.nan(.), 0)) %>% 
  rename(`Time (hours)` = Hours) %>% 
  mutate(prey_general = "Krill",
         Study_Area = "SoCal",
         Region = "Eastern North Pacific",
         tag_type = "DTAG")


load("~/Documents/Research Data/Whale research/ShirelCh2/rates_DTAG_problems addressed.RData")

lunge_rates_DTAG_problems_addressed <- dtag_lunges_long %>% 
  mutate_at(vars(Rate), ~replace(., is.nan(.), 0)) %>% 
  rename(`Time (hours)` = Hours) %>% 
  mutate(prey_general = "Krill",
         Study_Area = "SoCal",
         Region = "Eastern North Pacific",
         tag_type = "DTAG")

lunge_rates_all <- lunge_rates_DTAG_problems_addressed %>% 
  bind_rows(lunge_rates_CATS) %>% 
  mutate(SpeciesCode = substr(ID, 1, 2))

## REMOVE BAD DEPLOYMENTS ###
bad_ID <- read_csv("Bad ID.csv")

#put all DTAG deployments together 
lunge_rates_all <- lunge_rates_DTAG_problems_addressed %>% 
  bind_rows(lunge_rates_CATS) %>% 
  mutate(SpeciesCode = substr(ID, 1, 2)) %>% 
  anti_join(bad_ID, by = "ID")



# READ IN and COMBINE DATA
# Species-specific average length data (from Shirel's paper) to recalculate average engulfment capacity----
v_data <- read_csv("MWmeasurements.csv") %>% 
  group_by(Species) %>% 
  dplyr::summarize(med_TLm = median(TLm)) %>% 
  rename(CommonName = Species) %>% 
  mutate(SpeciesCode = case_when(CommonName ==  "Blue Whale" ~ "bw",
                                 CommonName == "Fin Whale"~ "bp",
                                 CommonName ==  "Humpback Whale" ~ "mn",
                                 CommonName == "Minke Whale" ~ "bb", 
                                 CommonName == "Bryde's Whale" ~ "be",
                                 CommonName == "Sei Whale" ~ "bs"))
# # v_data$L <- v_data$MW*0.9766  #creates column that converts MW (kg) to liters

# Allometric equations from Shirel's paper----
# creating fucntions from Shirel's paper for MW (in kg) for engulfment capacity in liters for each species where we have a known length
engulf_allo <- tribble(
  ~SpeciesCode, ~slope,   ~intercept,
  "bb",     3.10910,  0.69969,
  "be",     3.1453,   0.5787,
  "bs",     3.05591,   0.77219,
  "bp",     3.54883,  0.15604,
  "bw",     3.667316, -0.014078,
  "mn",     3.24603,  0.85934
)


# Species specific krill prey weight per m^3----
#from DEC's file BaleenWhaleForagingDistBigKrill100Bins, I think this is the NULL distribution
# Gives mean biomass of krill in kg per m^3----
prey_dist <- tribble(
  ~SpeciesCode, ~ln_mean,          ~ln_sd,
  "bb",     log(10^-0.302053984),  log(10^(0.402095747^2))^0.5,    # E. superba
  "bp",     log(10^-0.207001968),  log(10^(0.397598067^2))^0.5,    # T.spin
  "bw",     log(10^-0.200903497),  log(10^(0.391739563^2))^0.5,    # T.spin
  "mn",     log(10^-0.21552581),  log(10^(0.400348263^2))^0.5      # T.spin
)

prey_dist_ENP <- tribble(
  ~SpeciesCode,     ~ln_mean,             ~ln_sd,
  "Best_lower",     log(10^0.021189299),  log(10^(0.255272505^2))^0.5,    # T.spin, ALL FROM MRY
  "Best_upper",     log(10^0.204119983),  log(10^(0.113943352^2))^0.5,    # T.spin, ALL FROM MRY
  "Hypothetical_low",     log(10^-0.74836178),  0.7374944     #log(10^(-0.514278574)^2)^0.5      # had to calculate manually or NaN is produced
)


prey_dist_ENP <- tribble(
  ~SpeciesCode,     ~ln_mean, ~ln_sd,
  "Best_lower",     log(1.05),  log(1.8),    # T.spin, ALL FROM MRY
  "Best_upper",     log(1.6),  log(1.3),    # T.spin, ALL FROM MRY
  "Hypothetical_low",  log(0.1785),  log(0.306)     #log(10^(-0.514278574)^2)^0.5      # had to calculate manually or NaN is produced
)
  
# example of what a blue whale m3 krill density distribution looks like ----
index = 1:10000
MRY_hyp_low_prey_dens_m3 <- rlnorm(1e4, log(1.05) + log(0.17),   log(1.8))  # this hypothetical low distribution used extremely large ENP krill (28mm); AND target strength for E. superba, which is bigger than 28mm 
MRY_best_lower_prey_dens_m3 <- rlnorm(1e4, log(1.05),  log(1.8)) 
MRY_best_upper_prey_dens_m3 <- rlnorm(1e4, log(1.6),  log(1.3)) 
ex_prey_dens <- as.data.frame(cbind(index, MRY_hyp_low_prey_dens_m3, MRY_best_lower_prey_dens_m3, MRY_best_upper_prey_dens_m3))

ex_prey_dens <- ggplot(ex_prey_dens) + 
  #geom_histogram(binwidth = 0.1, fill = "gray80") +
  #geom_density(color = "blue") +
  #geom_freqpoly(aes(MRY_hyp_low_prey_dens_m3), binwidth = 0.1, color = "gray60") +
  geom_freqpoly(aes(MRY_hyp_low_prey_dens_m3), binwidth = 0.1, color = "gray20") +
  geom_freqpoly(aes(MRY_best_lower_prey_dens_m3), binwidth = 0.1, color = "blue") +
  geom_freqpoly(aes(MRY_best_upper_prey_dens_m3), binwidth = 0.1, color = "red") +
  labs(x = bquote('krill biomass'~(kg~per~m^3))) +
  theme_classic(base_size = 18)
ex_prey_dens




# Whale population data---- 
#Current data from IUCN 2019 Redlist, whaling data compiled in Rocha et al. 2014
pop_data <- read_excel("Filtration project_Whale population and feeding information.xlsx", sheet = 1)


#Read in tag guide----
tag_guide <- read_excel("TAG GUIDE_9.5.19.xlsx", skip = 2) %>%  # Skips first two rows
  rename(Study_Area = `Study_Area     _`,
         SpeciesCode = `Spec      _`,
         whaleLength = `Drone  _`) 

tag_guide_ENP <- tag_guide %>% 
  filter(Study_Area %in% c("Monterey", "Cordell Bank", "SoCal", "San Diego", "WA Coast", "Alaska"))
#View(tag_guide_ENP)  # this is for CATS tags only, need to add in DTags for full dataset

# Master filtration rate file----
filtration_master <- lunge_rates_all %>%
  left_join(select(tag_guide, ID, SpeciesCode, Study_Area, whaleLength), by = c("ID", "SpeciesCode")) %>%
  mutate(Study_Area = coalesce(Study_Area.x, Study_Area.y)) %>% 
  select(-c(Study_Area.x, Study_Area.y)) %>% 
  filter(SpeciesCode %in% c("bb", "be", "bp", "bw", "mn", "bs")) %>% 
  mutate(
    Year = substr(ID, 3, 4),
    whaleLength = parse_number(whaleLength),
    Study_Area = replace_na(Study_Area, "SoCal"),
    CommonName = case_when(
      SpeciesCode == "bw" ~ "Blue Whale",
      SpeciesCode == "bp" ~ "Fin Whale",
      SpeciesCode == "bs" ~ "Sei Whale",
      SpeciesCode == "mn" ~ "Humpback Whale",
      SpeciesCode %in% c("ba", "bb") ~ "Minke Whale", 
      TRUE ~ "Bryde's Whale"),
    Species = case_when(
      SpeciesCode == "bw" ~ "Balaenoptera musculus",
      SpeciesCode == "bp" ~ "Balaenoptera physalus",
      SpeciesCode == "mn" ~ "Megaptera novaeangliae",
      SpeciesCode %in% c("bb","ba") ~ "Balaenoptera bonaerensis", 
      SpeciesCode == "be" ~ "Balaenoptera edeni",
      SpeciesCode == "bs" ~ "Balaenoptera borealis"),
    Region = case_when(
      Study_Area %in% c("Monterey", "SoCal", "Cordell Bank", "San Diego", "WA Coast", "Alaska", "Everett")  ~ "Eastern North Pacific",
      Study_Area %in% c("Stellwagen", "Norway", "Azores", "Greenland") ~ "North Atlantic",
      Study_Area == "South Africa" ~ "South Africa",
      Study_Area == "Antarctic" ~ "Antarctic",
      Study_Area == "Chile" ~ "Chile",
      Study_Area == "Falklands" ~ "Falklands")) %>%  
  # Join population numbers
  left_join(select(pop_data, -c(SpeciesCode, `Current Range`)), by = "Species") %>% 
  # Join species-median size data
  left_join(select(v_data, -CommonName), by = "SpeciesCode") %>% 
  # Join allometric equations
  left_join(engulf_allo, by = "SpeciesCode") %>% 
  # Calculate engulfment volumes
  mutate(
    BestLengthEst = coalesce(whaleLength, med_TLm),
    Engulfment_L = BestLengthEst ^ slope * 10 ^ intercept * 0.9766,
    EngulfVolPerHr = Engulfment_L*Rate) %>% 
  left_join(prey_dist, by = "SpeciesCode") %>% 
  ungroup %>% 
  mutate(prey_hyp_low_lnmean = -1.72316668,
         prey_hyp_low_lnsd = 0.7374944,
         prey_best_low_lnmean = 0.04879016,
         prey_best_low_lnsd = 0.3873574,
         prey_best_upper_lnmean = 0.47000363,
         prey_best_upper_lnsd = 0.1729007)


filtration_master %>%
  group_by(Species) %>%
  summarise(mean_length = median(whaleLength))




# plots of raw data----
  
pal <- c("B. bonaerensis" = "firebrick3", "B. borealis" = "goldenrod2", "B. edeni" = "darkorchid3",  "M. novaeangliae" = "gray30", "B. physalus" = "chocolate3", "B. musculus" = "dodgerblue2")
  
filter(Region == "Eastern North Pacific", ID != "bw180904-44") %>% 
  group_by(ID, Species) %>% 
  summarise(whaleLength = first(whaleLength)) %>% 
  ungroup %>% 
  mutate(sp_lbl = factor(abbr_binom(Species)) %>% fct_rev) %>% 
  
  
All_droned_lengths <- filtration_master %>% 
  #filter(SpeciesCode %in% c("bw", "bp", "mn")) %>% 
  filter(Region == "Eastern North Pacific", ID != "bw180904-44") %>% 
  group_by(ID, Species) %>% 
  summarise(whaleLength = first(whaleLength)) %>% 
  ungroup %>% 
  mutate(sp_lbl = factor(abbr_binom(Species)) %>% fct_rev) %>% 
  ggplot(aes(x = sp_lbl, 
             y = whaleLength,
             fill = abbr_binom(Species))) +
  geom_flat_violin(position = position_nudge(x = 0.1, y = 0), alpha = .8) +
  geom_boxplot(width = .1, outlier.shape = NA, alpha = 0.5) +
  geom_point(position = position_jitter(width = .05), alpha = 0.6) +
  coord_flip() +
  scale_fill_manual(values = pal) +
  labs(x = "Species",
       y = "Measured length (m)") +
  theme_classic(base_size = 18) +
  theme(legend.position = "none",
        axis.text.y = element_text(face = "italic"))
All_droned_lengths
  
dev.copy2pdf(file="All_droned_lengths.pdf", width=12, height=8)


Engulfment_capacity <- filtration_master %>% 
  filter(Region == "Eastern North Pacific", ID != "bw180904-44") %>% 
  drop_na(whaleLength) %>% 
  group_by(ID, Species, Engulfment_L) %>% 
  summarise(whaleLength = first(whaleLength)) %>%
  mutate(Engulfment_m3 = Engulfment_L/1000) %>%
  ungroup %>% 
  ggplot(aes(x = fct_reorder(abbr_binom(Species), Engulfment_m3), y = Engulfment_m3,
             fill = abbr_binom(Species))) +
  geom_flat_violin(position = position_nudge(x = 0.075, y = 0), alpha = .8) +
  geom_boxplot(width = .1, outlier.shape = NA, alpha = 0.5) +
  geom_point(position = position_jitter(width = .05), alpha = 0.6) +
  coord_flip() +
  scale_fill_manual(values = pal) +
  labs(x = "Species",
       y = bquote('Engulfment capacity'~(m^3))) +
  theme_classic(base_size = 18) +
  theme(legend.position = "none",
        axis.text.y = element_text(face = "italic"))
Engulfment_capacity

dev.copy2pdf(file="Engulfment_capacity_ENP.pdf", width=12, height=8)

#plot of feeding rates per hour for ENP species 

Feeding_rate_h <- filtration_master %>% 
  filter(prey_general == "Krill", Phase == "Total") %>%      # 
  group_by(ID, Species, Engulfment_L, Phase, Rate, prey_general, Year) %>% 
  summarise(whaleLength = first(whaleLength)) %>%
  mutate(Engulfment_m3 = Engulfment_L/1000) %>%
  ungroup %>% 
  ggplot(aes(x = fct_reorder(abbr_binom(Species), Rate), y = Rate,
             fill = abbr_binom(Species))) +
  geom_flat_violin(position = position_nudge(x = 0.1, y = 0), alpha = .8) +
  geom_boxplot(width = .1, guides = FALSE, outlier.shape = NA, alpha = 0.5) +
  #geom_point(position = position_jitter(width = .05), alpha = 0.6) +
  #facet_grid(.~Year, scales = "free") +
  coord_flip() +
  scale_fill_manual(values = pal) +
  labs(x = "Species",
       y = "Feeding rate (lunges per hour)") +
  theme_classic(base_size = 18) +
  theme(legend.position = "none",
        axis.text.y = element_text(face = "italic"))
Feeding_rate_h

dev.copy2pdf(file="Feeding_rate_h.pdf", width=12, height=8)


# for University of Washington application ----

JAF_data <- tribble(
  ~ID, ~Species, ~SpeciesCode, ~Phase, ~Rate, ~prey_general, ~Year,
  "bm151016-TDR7",    "Balaenoptera musculus", "bw", "Total", 5.21, "Krill",  "15",
  "bm151016-TDR5",    "Balaenoptera musculus", "bw", "Total", 4.19, "Krill",  "15",
  "bm150819-TDR5",    "Balaenoptera musculus", "bw", "Total", 6.92, "Krill",  "15",
  "bm150818-8",    "Balaenoptera musculus", "bw", "Total", 5.70, "Krill",  "15"
)


Feeding_rate_bw_h <- filtration_master %>% 
  filter(SpeciesCode == "bw",
           Region == "Eastern North Pacific", 
         prey_general == "Krill", 
         Phase == "Total", 
         Rate < 31,
         Year != "12") %>%      #  %in% c("Day", "Night")
  group_by(ID, Species, SpeciesCode, Phase, Rate, prey_general, Year) %>% 
  ungroup %>% 
  select(ID, Species, Phase, Rate, prey_general, Year) %>% 
  bind_rows(JAF_data) %>% 
  mutate(YearFull = paste0("20", Year)) %>% 
  ggplot(aes(x = fct_reorder(abbr_binom(Species), Rate), y = Rate,
             fill = abbr_binom(Species))) +
  geom_flat_violin(position = position_nudge(x = 0.1, y = 0), alpha = .8) +
  geom_boxplot(width = .1, guides = FALSE, outlier.shape = NA, alpha = 0.5) +
  geom_point(position = position_jitter(width = .05), alpha = 0.6) +
  facet_grid(.~YearFull, scales = "free") +
  #coord_flip() +
  scale_fill_manual(values = pal) +
  labs(y = expression(italic('B. musculus')~~'feeding rate'~(lunges~hr^-1))) + #bquote('Estimated water filtered'~(m^3~d^-1))
  theme_classic(base_size = 12) +
  theme(legend.position = "none",
        axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank())
Feeding_rate_bw_h


################################
## CREATE SAMPLING FUNCTION----
################################

#determining daily feeding rates ----

# Get a sample of whale lengths
sample_length <- function(sp_code, size) {
  # Check species code is valid
  if (!sp_code %in% c("bw", "bp", "mn", "bb")) {
    stop(sprintf("%s is an invalid species code", sp_code))
  }
  # Filter to species
  lengths <- filtration_master %>% 
    filter(SpeciesCode == sp_code) %>% 
    drop_na(whaleLength)
  # Verify available whale lengths
  if (nrow(lengths) == 0) {
    stop(sprintf("No lengths available for %s", sp_code))
  }
  # Draw sample
  sample(lengths$whaleLength, size, replace = TRUE)
}

# Seems to be working
sample_rates <- function(rows, keys) {
  rows_wide <- rows %>% 
    select(ID, Phase, Rate, `Time (hours)`) %>% 
    pivot_wider(names_from = Phase, values_from = c(Rate, `Time (hours)`))
  
  # Skip groups with one animal
  if(nrow(rows_wide) == 1) return(tibble())
  
  sample2 <- function(x, prob, size, replace) {
    tryCatch({
      if (all(prob == 0)) {
        0
      } else {
        sample(x, prob = prob, size = size, replace = replace)
      }
    }, error = function(e) browser())
  }
  
  mass_per_day <- function(rate, capacity, lnmean, lnsd) {
    densities <- rlnorm(rate, lnmean, lnsd)
    sum(capacity * densities)
  }
  
  # Sample size
  sz <- 10000
  result <- tibble(day_rate = sample2(rows_wide$Rate_Day, prob = rows_wide$`Time (hours)_Day`, size = sz, replace = TRUE),
                   tw_rate = sample2(rows_wide$Rate_Twilight, prob = rows_wide$`Time (hours)_Twilight`, size = sz, replace = TRUE),
                   night_rate = sample2(rows_wide$Rate_Night, prob = rows_wide$`Time (hours)_Night`, size = sz, replace = TRUE),
                   daily_rate = floor(day_rate*14 + tw_rate*3 + night_rate *7),
                   length_distrib = sample_length(keys$SpeciesCode, sz),
                   slope = rows$slope[1],
                   intercept = rows$intercept[1],
                   measured_engulfment_cap_m3 = (length_distrib ^ slope * 10 ^ intercept * 0.9766)/1000,
                   prey_mass_per_day_hyp_low_kg = map2_dbl(daily_rate, measured_engulfment_cap_m3, mass_per_day, 
                                                   lnmean = rows$prey_hyp_low_lnmean[1], 
                                                   lnsd = rows$prey_hyp_low_lnsd[1]),
                   prey_mass_per_day_best_low_kg = map2_dbl(daily_rate, measured_engulfment_cap_m3, mass_per_day, 
                                                           lnmean = rows$prey_best_low_lnmean[1], 
                                                           lnsd = rows$prey_best_low_lnsd[1]),
                   prey_mass_per_day_best_upper_kg = map2_dbl(daily_rate, measured_engulfment_cap_m3, mass_per_day, 
                                                            lnmean = rows$prey_best_upper_lnmean[1], 
                                                            lnsd = rows$prey_best_upper_lnsd[1]),
                   prey_mass_per_lunge = prey_mass_per_day_best_low_kg / daily_rate)
}

d_strapped <- filtration_master %>% 
  filter(prey_general == "Krill") %>% 
  group_by(Species, SpeciesCode, prey_general, Year, Region) %>% 
  group_modify(sample_rates) %>% 
  ungroup 




# preliminary plots ----

pal <- c("B. bonaerensis" = "firebrick3", "B. borealis" = "goldenrod2", "B. edeni" = "darkorchid3",  "M. novaeangliae" = "gray30", "B. physalus" = "chocolate3", "B. musculus" = "dodgerblue2")


Measured_length <- ggplot(d_strapped, 
                     aes(x = fct_reorder(abbr_binom(Species), length_distrib), y = length_distrib, 
                         fill = abbr_binom(Species))) +
  geom_flat_violin(position = position_nudge(x = 0.1, y = 0), alpha = .8) +
  geom_boxplot(width = .1, guides = FALSE, outlier.shape = NA, alpha = 0.5) +
  coord_flip() + 
  scale_fill_manual(values = pal) +
  labs(x = "Species",
       y = "Measured length (m)") + 
  theme_classic(base_size = 14) +
  theme(legend.position = "none",
        axis.text.y = element_text(face = "italic"))
Measured_length


Daily_rate_bw_yearly <- d_strapped %>% 
  #filter(SpeciesCode %in% c("bw", "bp", "mn") & prey_general == "Krill") %>% 
  filter(SpeciesCode == "bw", 
           prey_general == "Krill", 
         Region == "Eastern North Pacific", 
         Year != "12") %>% 
  ggplot(aes(x = fct_reorder(abbr_binom(Species), daily_rate), y = daily_rate, 
             fill = abbr_binom(Species))) +
  geom_flat_violin(position = position_nudge(x = 0.1, y = 0), alpha = .8) +
  geom_boxplot(width = .1, guides = FALSE, outlier.shape = NA, alpha = 0.5) +
  geom_hline(yintercept = 219, linetype = "dashed") +
  #coord_flip() + 
  scale_fill_manual(values = pal) +
  #scale_y_continuous(breaks = seq(from = 0, to = 2500, by = 500)) +
  facet_grid(.~Year) +
  labs(y = expression(italic('B. musculus') ~~ 'lunges per day')) + 
  theme_classic(base_size = 18) +
  theme(legend.position = "none",
        axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank())
Daily_rate_bw_yearly



Daily_rate <- d_strapped %>% 
  filter(SpeciesCode %in% c("bw", "bp", "mn"), prey_general == "Krill", 
         Region == "Eastern North Pacific", 
         Year != "12") %>% 
  #filter(SpeciesCode == "bw" & prey_general == "Krill") %>% 
  ggplot(aes(x = fct_reorder(abbr_binom(Species), daily_rate), y = daily_rate, 
                             fill = abbr_binom(Species))) +
  geom_flat_violin(position = position_nudge(x = 0.1, y = 0), alpha = .8) +
  geom_boxplot(width = .1, guides = FALSE, outlier.shape = NA, alpha = 0.5) +
  coord_flip() + 
  scale_fill_manual(values = pal) +
  #scale_y_continuous(breaks = seq(from = 0, to = 2500, by = 500)) +
  labs(x = "Species",
       y = "Lunges per day") + 
  theme_bw(base_size = 18) +
  theme(legend.position = "none",
        axis.text.y = element_text(face = "italic"))
Daily_rate

dev.copy2pdf(file="Daily_rate.pdf", width=12, height=8)


Daily_filtration <- d_strapped %>%   
  filter(SpeciesCode %in% c("bw", "bp", "mn"), prey_general == "Krill", 
                             Region == "Eastern North Pacific", 
                             Year != "12") %>% 
  ggplot(aes(x = fct_reorder(abbr_binom(Species), measured_engulfment_cap_m3*daily_rate), y = measured_engulfment_cap_m3*daily_rate, 
                         fill = abbr_binom(Species))) +
  geom_flat_violin(position = position_nudge(x = 0.1, y = 0), alpha = .8) +
  geom_boxplot(width = .1, guides = FALSE, outlier.shape = NA, alpha = 0.5) +
  coord_flip() + 
  scale_fill_manual(values = pal) +
  ylim(0,60000) +
  labs(x = "Species",
       y = bquote('Estimated water filtered'~(m^3~d^-1))) + 
  theme_classic(base_size = 16) +
  theme(legend.position = "none",
        axis.text.y = element_text(face = "italic"))
Daily_filtration


Daily_biomass_ingested <- ggplot(filter(d_strapped, SpeciesCode != "bb")) +
  #hyp-low
  # geom_flat_violin(aes(x = fct_reorder(abbr_binom(Species), prey_mass_per_day_hyp_low_kg), y = prey_mass_per_day_hyp_low_kg/1000, 
  #                      fill = abbr_binom(Species)), color = NA, position = position_nudge(x = 0.2, y = 0), alpha = .4, adjust = 2) +
  # geom_boxplot(aes(x = fct_reorder(abbr_binom(Species), prey_mass_per_day_hyp_low_kg), y = prey_mass_per_day_hyp_low_kg/1000, 
  #                  fill = abbr_binom(Species)), color = "gray20", width = .1, guides = FALSE, outlier.shape = NA, alpha = 0.1,
  #              position = position_nudge(x = -0.12, y = 0)) +
  #best-low *our best estimate*
  geom_flat_violin(aes(x = fct_reorder(abbr_binom(Species), prey_mass_per_day_best_low_kg), y = prey_mass_per_day_best_low_kg/1000, 
                       fill = abbr_binom(Species)), position = position_nudge(x = 0.2, y = 0), alpha = 1, adjust = 2) +
  geom_boxplot(aes(x = fct_reorder(abbr_binom(Species), prey_mass_per_day_best_low_kg), y = prey_mass_per_day_best_low_kg/1000, 
                   fill = abbr_binom(Species)), width = .1, guides = FALSE, outlier.shape = NA, alpha = 0.8,
               position = position_nudge(x = 0.12, y = 0)) +
  #best-upper
  # geom_flat_violin(aes(x = fct_reorder(abbr_binom(Species), prey_mass_per_day_best_upper_kg), y = prey_mass_per_day_best_upper_kg/1000, 
  #                      fill = abbr_binom(Species)), color = NA, position = position_nudge(x = 0.2, y = 0), alpha = .4, adjust = 2) +
  # geom_boxplot(aes(x = fct_reorder(abbr_binom(Species), prey_mass_per_day_best_upper_kg), y = prey_mass_per_day_best_upper_kg/1000, 
  #                  fill = abbr_binom(Species)), color = "red", width = .1, guides = FALSE, outlier.shape = NA, alpha = 0.1) +
  ylim(0,100) +
  coord_flip() +
  scale_fill_manual(values = pal) +
  labs(x = "Species",
       y = bquote('Estimated prey consumed'~(tonnes~d^-1))) +
  theme_classic(base_size = 20) +
  theme(legend.position = "none",
        axis.text.y = element_text(face = "italic"))
Daily_biomass_ingested

dev.copy2pdf(file="Daily_biomass_ingested.pdf", width=14, height=8)


Rate_by_length <- ggplot(d_strapped, 
                         aes(x = log10(length_distrib), y = log10(daily_rate))) +
  #geom_smooth(method = "lm") +
  geom_abline(intercept = 0, slope = -1, linetype ="dashed", size = 1.15) + 
  #geom_point() +
  scale_color_manual(values = pal) +
  theme_classic(base_size = 18)
Rate_by_length


MW_by_length <- ggplot(d_strapped, 
                         aes(log10(length_distrib), log10(measured_engulfment_cap_m3))) +
  geom_smooth(method = "lm") +
  geom_point() +
  scale_color_manual(values = pal) +
  theme_classic(base_size = 18)
MW_by_length


MN_ENP_daily_rate <- filtration_master %>% 
  filter(SpeciesCode == "mn" & Region == "Eastern North Pacific") %>% 
  group_by(Species) %>% 
  group_modify(sample_rates) %>% 
  ggplot(aes(x = prey_general, y = daily_rate, fill = prey_general)) +
  geom_flat_violin(position = position_nudge(x = 0.1, y = 0), alpha = .8) +
  geom_boxplot(width = .1, guides = FALSE, outlier.shape = NA, alpha = 0.5) +
  coord_flip() + 
  #scale_fill_manual(values = pal) +
  labs(x = "Species",
       y = "Lunges per day") + 
  theme_classic(base_size = 14) +
  theme(legend.position = "none")





# graphing Irvine et al feeding rates

Irvine_data <- read_csv(file = "Irvine et al. 2019_med_dur_tag_data.csv")

Irvine_feeding_rates <- Irvine_data %>% 
  group_by(ID, Species, Tag_duration_d) %>% 
  summarise(Total_lunges_fulltag = sum(Total_lunges)) %>% 
  ungroup %>% 
  mutate(daily_rate = Total_lunges_fulltag / Tag_duration_d) %>% 
  ggplot(aes(x = fct_reorder(abbr_binom(Species), daily_rate), y = daily_rate,
             fill = abbr_binom(Species))) +
  geom_flat_violin(position = position_nudge(x = 0.1, y = 0), alpha = .8) +
  geom_boxplot(width = .1, guides = FALSE, outlier.shape = NA, alpha = 0.5) +
  geom_point(position = position_jitter(width = .05), alpha = 0.6) +
  coord_flip() +
  scale_fill_manual(values = pal) +
  labs(x = "Species",
       y = "Feeding rate (Lunges per day)") +
  theme_classic(base_size = 18) +
  theme(legend.position = "none",
        axis.text.y = element_text(face = "italic"))
Irvine_feeding_rates
















# Extra code below here ----


# 
# DTAG2 <- pivot_longer_spec(lunge_rates,
#                                tribble(
#                                  ~.name,            ~.value,
#                                  "Lunges_Total",    "Lunges",
#                                  "Lunges_Day",      "Lunges",
#                                  "Lunges_Night",    "Lunges",
#                                  "Lunges_Twilight", "Lunges",
#                                  "Hours_Total",     "Hours",
#                                  "Hours_Day",       "Hours",
#                                  "Hours_Night",     "Hours",
#                                  "Hours_Twilight",  "Hours",
#                                  "Rate_Total",      "Rate",
#                                  "Rate_Day",        "Rate",
#                                  "Rate_Night",      "Rate",
#                                  "Rate_Twilight",   "Rate"
#                                ))
#                              
# dtag_spec <- lunge_rates %>% 
#   build_longer_spec(-ID,
#                     names_to = "Phase",
#                     values_to = c("Lunges", "Hours", "Rate")) %>% 
#   mutate(Phase = str_replace(Phase, ".*_(.*)", "\\1"))
# pivot_longer_spec(lunge_rates, dtag_spec) %>% View
# lunge_rates %>% pivot_longer()

# rows <- slice(filtration_master, 1:8)

rows_wide <- filtration_master %>% 
  select(ID, Species, Phase, Rate, `Time (hours)`) %>% 
  pivot_wider(names_from = Phase, values_from = c(Rate, `Time (hours)`))

result <- tibble(day_rate = base::sample(rows_wide$Rate_Day, prob = rows_wide$`Time (hours)_Day`, size = 1e4, replace = TRUE),
                 tw_rate = base::sample(rows_wide$Rate_Twilight, prob = rows_wide$`Time (hours)_Twilight`, size = 1e4, replace = TRUE),
                 night_rate = base::sample(rows_wide$Rate_Night, prob = rows_wide$`Time (hours)_Night`, size = 1e4, replace = TRUE),
                 daily_rate = day_rate*16 + tw_rate*2 + night_rate *6)


# tag_guide2 <- tag_guide %>% 
#   mutate(    
#     Species = case_when(
#       SpeciesCode == "bw" ~ "Balaenoptera musculus",
#       SpeciesCode == "bp" ~ "Balaenoptera physalus",
#       SpeciesCode == "mn" ~ "Megaptera novaeangliae",
#       SpeciesCode %in% c("bb","ba") ~ "Balaenoptera bonaerensis", 
#       SpeciesCode == "be" ~ "Balaenoptera edeni",
#       SpeciesCode == "bs" ~ "Balaenoptera borealis"),
#     whaleLength = parse_number(whaleLength)) %>% 
#   select(Species, whaleLength) %>%  
#   na.omit() %>% 
#   filter(whaleLength < 40)
#     
# pal <- c("B. bonaerensis" = "firebrick3", "B. borealis" = "goldenrod2", "B. edeni" = "darkorchid3",  "M. novaeangliae" = "gray30", "B. physalus" = "chocolate3", "B. musculus" = "dodgerblue2")
# 
# 



#plot of droned lengths
drone_master <- filtration_master %>% 
  filter(Phase == "Total") %>% 
  drop_na(whaleLength) 

# %>% 
#   group_by(Species) %>% 
#   summarise(mean_length = mean(whaleLength),
#             SE_length = sd(whaleLength)/sqrt(count(unique(ID))))

Droned_lengths <- ggplot(drone_master, 
                         aes(x = fct_reorder(abbr_binom(Species), whaleLength), y = whaleLength, 
                             fill = abbr_binom(Species))) +
  geom_flat_violin(position = position_nudge(x = 0.1, y = 0), alpha = .8) +
  geom_boxplot(width = .1, guides = FALSE, outlier.shape = NA, alpha = 0.5) +
  geom_point(position = position_jitter(width = .05), size = .5, alpha = 0.6) +
  coord_flip() + 
  scale_fill_manual(values = pal) +
  labs(x = "Species",
       y = "Measured length (m)") + 
  theme_classic(base_size = 16) +
  theme(legend.position = "none",
        axis.text.y = element_text(face = "italic"))
Droned_lengths

ggsave("Droned_lengths.tiff", width = 8, height = 12, units = "in")
dev.copy2pdf(file="Droned_lengths.pdf", width=12, height=8)



# Master filtration rate file
filtration_master <- lunge_rates %>% 
  left_join(select(tag_guide, ID, SpeciesCode, Study_Area, whaleLength), 
            by = "ID") %>% 
  mutate(   
    # Make whale length a number
    whaleLength = parse_number(whaleLength),
    SpeciesCode = substr(ID,1,2),
    # Replace NAs in location with "SoCal"
    Study_Area = replace_na(Study_Area, "SoCal"),
    CommonName = case_when(
      SpeciesCode == "bw" ~ "Blue Whale",
      SpeciesCode == "bp" ~ "Fin Whale",
      SpeciesCode == "bs" ~ "Sei Whale",
      SpeciesCode == "mn" ~ "Humpback Whale",
      SpeciesCode %in% c("ba", "bb") ~ "Minke Whale", 
      TRUE ~ "Bryde's Whale"),
    Species = case_when(
      SpeciesCode == "bw" ~ "Balaenoptera musculus",
      SpeciesCode == "bp" ~ "Balaenoptera physalus",
      SpeciesCode == "mn" ~ "Megaptera novaeangliae",
      SpeciesCode %in% c("bb","ba") ~ "Balaenoptera bonaerensis", 
      SpeciesCode == "be" ~ "Balaenoptera edeni",
      SpeciesCode == "bs" ~ "Balaenoptera borealis"),
    Region = case_when(
      Study_Area %in% c("Monterey", "SoCal", "Cordell Bank", "San Diego", "WA Coast", "Alaska", "Everett")  ~ "Eastern North Pacific",
      Study_Area %in% c("Stellwagen", "Norway", "Azores", "Greenland") ~ "North Atlantic",
      Study_Area == "South Africa" ~ "South Africa",
      Study_Area == "Antarctic" ~ "Antarctic",
      Study_Area == "Chile" ~ "Chile",
      Study_Area == "Falklands" ~ "Falklands")) %>% 
  # Join population numbers
  left_join(select(pop_data, -c(SpeciesCode, `Current Range`)), by = "Species") %>% 
  # Join species-median size data
  left_join(select(v_data, -CommonName), by = "SpeciesCode") %>% 
  # Join allometric equations
  left_join(engulf_allo, by = "SpeciesCode") %>% 
  # Calculate engulfment volumes
  mutate(
    BestLengthEst = coalesce(whaleLength, med_TLm),
    Engulfment_L = BestLengthEst ^ slope * 10 ^ intercept * 0.9766,
    EngulfVolPerHr = Engulfment_L*Rate) %>% 
  left_join(prey_dist, by = "SpeciesCode") %>% 
  ungroup


source("https://gist.githubusercontent.com/benmarwick/2a1bb0133ff568cbe28d/raw/fb53bd97121f7f9ce947837ef1a4c65a73bffb3f/geom_flat_violin.R")
raincloud_theme = theme(
  text = element_text(size = 10),
  axis.title.x = element_text(size = 16),
  axis.title.y = element_text(size = 16),
  axis.text = element_text(size = 14),
  axis.text.x = element_text(angle = 45, vjust = 0.5),
  legend.title=element_text(size=16),
  legend.text=element_text(size=16),
  legend.position = "right",
  plot.title = element_text(lineheight=.8, face="bold", size = 16),
  panel.border = element_blank(),
  panel.grid.minor = element_blank(),
  panel.grid.major = element_blank(),
  axis.line.x = element_line(colour = 'black', size=0.5, linetype='solid'),
  axis.line.y = element_line(colour = 'black', size=0.5, linetype='solid'))



select(Region, Species, ID, Phase, Rate, Dur = `Time (hours)`) %>%

d_ENP_mn = filter(filtration_master, Phase == "Day" & Region == "Eastern North Pacific" & SpeciesCode == "mn" & prey_general == "Krill")
t_ENP_mn = filter(filtration_master, Phase == "Twilight" & Region == "Eastern North Pacific" & SpeciesCode == "mn" & prey_general == "Krill")
n_ENP_mn = filter(filtration_master, Phase == "Night" & Region == "Eastern North Pacific" & SpeciesCode == "mn" & prey_general == "Krill")
d_ENP_bp = filter(filtration_master, Phase == "Day" & Region == "Eastern North Pacific" & SpeciesCode == "bp")
t_ENP_bp = filter(filtration_master, Phase == "Twilight" & Region == "Eastern North Pacific" & SpeciesCode == "bp")
n_ENP_bp = filter(filtration_master, Phase == "Night" & Region == "Eastern North Pacific" & SpeciesCode == "bp")
d_ENP_bw = filter(filtration_master, Phase == "Day" & Region == "Eastern North Pacific" & SpeciesCode == "bw")
t_ENP_bw = filter(filtration_master, Phase == "Twilight" & Region == "Eastern North Pacific" & SpeciesCode == "bw")
n_ENP_bw = filter(filtration_master, Phase == "Night" & Region == "Eastern North Pacific" & SpeciesCode == "bw")

  
mn_wgt_hourly_rates <- tibble(
  Day = base::sample(d_ENP_mn$Rate, prob = d_ENP_mn$`Time (hours)`, size = 1e4, replace = TRUE), 
  Twilight = base::sample(t_ENP_mn$Rate, prob = t_ENP_mn$`Time (hours)`, size = 1e4, replace = TRUE), 
  Night = base::sample(n_ENP_mn$Rate, prob = n_ENP_mn$`Time (hours)`, size = 1e4, replace = TRUE),
  Species = "M. novaeangliae")


bp_wgt_hourly_rates <- tibble(
  Day = base::sample(d_ENP_bp$Rate, prob = d_ENP_bp$`Time (hours)`, size = 1e4, replace = TRUE), 
#  Twilight = base::sample(t_ENP_bp$Rate, prob = t_ENP_bp$`Time (hours)`, size = 1e4, replace = TRUE),   #doesnt work because theres no data 
#  Night = base::sample(n_ENP_bp$Rate, prob = n_ENP_bp$`Time (hours)`, size = 1e4, replace = TRUE),      #doesnt work because theres no data
  Species = "B. physalus")

bw_wgt_hourly_rates <- tibble(
  Day = base::sample(rows$Rate, prob = rows$`Time (hours)`, size = 1e4, replace = TRUE), 
  Twilight = base::sample(t_ENP_bw$Rate, prob = t_ENP_bw$`Time (hours)`, size = 1e4, replace = TRUE), 
  Night = base::sample(n_ENP_bw$Rate, prob = n_ENP_bw$`Time (hours)`, size = 1e4, replace = TRUE),
  Species = "B. musculus")


ENP_wgt_hourly_rates <- rbind(mn_wgt_hourly_rates, bw_wgt_hourly_rates) %>% 
  mutate(daily_rate = Day*16 + Twilight*2 + Night *6,
         Species = factor(Species))








ggplot(ENP_wgt_hourly_rates, aes(x = Species, y = daily_rate, fill = Species)) +
  geom_violin() +
  geom_jitter(width = 0.15, size = 0.1) +
  theme_classic()

ENP_daily_rates <- ggplot(ENP_wgt_hourly_rates,
                          aes(daily_rate, Species, fill = Species))+
  #geom_flat_violin(position = position_nudge(x = .2, y = 0),adjust = 2)+
  geom_density() +
  #geom_violin() +
  geom_point(position = position_jitter(width = .15), size = .25)+
  scale_fill_manual(values = pal) +
  facet_grid(.~Species) +
  theme_classic(base_size = 14)
ENP_daily_rates



# Max's complicated stuff ----
day_hours <- tribble(
  ~Location, ~d_hours,   ~Tw_hours, ~N_hours,
  "Temperate",     16, 2, 6, 
  "Polar",     19,  4, 1
)

d = filter(filtration_master, Phase == "Day")
t = filter(filtration_master, Phase == "Twilight")
n = filter(filtration_master, Phase == "Night")

filtration_master %>% 
  ungroup %>% 
  filter(Region %in% c("Antarctic", "Eastern North Pacific")) %>% 
  select(Region, Species, ID, Phase, Rate, Dur = `Time (hours)`) %>%
  group_by(Species, Region) %>% 
  group_modify(function(data, key) {
    d <- filter(data, Phase == "Day")
    t <- filter(data, Phase == "Twilight")
    n <- filter(data, Phase == "Night")
    
    if (nrow())
      
      sz <- 1e2
    tryCatch(
      tibble(
        Day = base::sample(d$Rate, prob = d$Dur, size = sz, replace = TRUE), 
        Twilight = base::sample(t$Rate, prob = t$Dur, size = sz, replace = TRUE), 
        Night = base::sample(n$Rate, prob = n$Dur, size = sz, replace = TRUE)),
      error = function(e) browser())
  }) %>% View





